### PR TITLE
Potential logo

### PR DESCRIPTION
**Pull request by adryd325**
solves #13

clink

### CODE REVIEW

**Comment by Mstrodl** [comment]
You should put this in the README :eyes:

**Review by Mstrodl — APPROVED** [review]
I like it, but would love to see @WillNilges opinions

**Review by WillNilges — COMMENTED** [review]
I like the logo! Not sure if it'll work in dark mode like this, though?

image

Make sure it works in dark mode, and I'll approve.

**Comment by adryd325** [comment]
How's this clink-gray

**Review by WillNilges — APPROVED** [review]

**Comment by Mstrodl** [comment]
:shipit:

**Pull request merged**
