### PR TITLE
Haha refactor go brrrr

### PR DESCRIPTION
**Pull request by Mstrodl**
I um.... Oops. I know this should've been multiple PRs, I just kept finding little tiny things to add and now look at me. Oops.

### CODE REVIEW

**Comment by Mstrodl** [comment]
Commits need to be squashed

**Comment by Mstrodl** [comment]
I would recommend `git diff 9041e857986da9a20e7a13cb4960bca67fd236d0 origin/feature/mstrodl/api-refactor` and `git diff v0.1.1 23c6753905af9a6ecc565ef32246ead5b37e51de` to be able to do something resembling effective review.... Sorry for the mess.

**Comment by Mstrodl** [comment]
Closes #11 
Closes #15 
Closes #7

**Review by WillNilges — APPROVED** [review]
:ship:

**Comment by Mstrodl** [comment]
YAY

**Pull request merged**
